/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OrganizadoresRouteImport } from './routes/organizadores'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as NewEventRouteImport } from './routes/newEvent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GenericRouteImport } from './routes/generic'
import { Route as EventDetailRouteImport } from './routes/eventDetail'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AcordeRouteImport } from './routes/acorde'
import { Route as AboutUsRouteImport } from './routes/aboutUs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const rootRouteImport = createRootRoute()

const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizadoresRoute = OrganizadoresRouteImport.update({
  id: '/organizadores',
  path: '/organizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const NewEventRoute = NewEventRouteImport.update({
  id: '/newEvent',
  path: '/newEvent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GenericRoute = GenericRouteImport.update({
  id: '/generic',
  path: '/generic',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDetailRoute = EventDetailRouteImport.update({
  id: '/eventDetail',
  path: '/eventDetail',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordeRoute = AcordeRouteImport.update({
  id: '/acorde',
  path: '/acorde',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/aboutUs',
  path: '/aboutUs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aboutUs': typeof AboutUsRoute
  '/acorde': typeof AcordeRoute
  '/calendario': typeof CalendarioRoute
  '/chats': typeof ChatsRoute
  '/eventDetail': typeof EventDetailRoute
  '/generic': typeof GenericRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/newEvent': typeof NewEventRoute
  '/notificaciones': typeof NotificacionesRoute
  '/organizadores': typeof OrganizadoresRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/soporte': typeof SoporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aboutUs': typeof AboutUsRoute
  '/acorde': typeof AcordeRoute
  '/calendario': typeof CalendarioRoute
  '/chats': typeof ChatsRoute
  '/eventDetail': typeof EventDetailRoute
  '/generic': typeof GenericRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/newEvent': typeof NewEventRoute
  '/notificaciones': typeof NotificacionesRoute
  '/organizadores': typeof OrganizadoresRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/soporte': typeof SoporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aboutUs': typeof AboutUsRoute
  '/acorde': typeof AcordeRoute
  '/calendario': typeof CalendarioRoute
  '/chats': typeof ChatsRoute
  '/eventDetail': typeof EventDetailRoute
  '/generic': typeof GenericRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/newEvent': typeof NewEventRoute
  '/notificaciones': typeof NotificacionesRoute
  '/organizadores': typeof OrganizadoresRoute
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/soporte': typeof SoporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aboutUs'
    | '/acorde'
    | '/calendario'
    | '/chats'
    | '/eventDetail'
    | '/generic'
    | '/home'
    | '/login'
    | '/newEvent'
    | '/notificaciones'
    | '/organizadores'
    | '/perfil'
    | '/register'
    | '/soporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aboutUs'
    | '/acorde'
    | '/calendario'
    | '/chats'
    | '/eventDetail'
    | '/generic'
    | '/home'
    | '/login'
    | '/newEvent'
    | '/notificaciones'
    | '/organizadores'
    | '/perfil'
    | '/register'
    | '/soporte'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aboutUs'
    | '/acorde'
    | '/calendario'
    | '/chats'
    | '/eventDetail'
    | '/generic'
    | '/home'
    | '/login'
    | '/newEvent'
    | '/notificaciones'
    | '/organizadores'
    | '/perfil'
    | '/register'
    | '/soporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  AcordeRoute: typeof AcordeRoute
  CalendarioRoute: typeof CalendarioRoute
  ChatsRoute: typeof ChatsRoute
  EventDetailRoute: typeof EventDetailRoute
  GenericRoute: typeof GenericRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NewEventRoute: typeof NewEventRoute
  NotificacionesRoute: typeof NotificacionesRoute
  OrganizadoresRoute: typeof OrganizadoresRoute
  PerfilRoute: typeof PerfilRoute
  RegisterRoute: typeof RegisterRoute
  SoporteRoute: typeof SoporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizadores': {
      id: '/organizadores'
      path: '/organizadores'
      fullPath: '/organizadores'
      preLoaderRoute: typeof OrganizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newEvent': {
      id: '/newEvent'
      path: '/newEvent'
      fullPath: '/newEvent'
      preLoaderRoute: typeof NewEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generic': {
      id: '/generic'
      path: '/generic'
      fullPath: '/generic'
      preLoaderRoute: typeof GenericRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventDetail': {
      id: '/eventDetail'
      path: '/eventDetail'
      fullPath: '/eventDetail'
      preLoaderRoute: typeof EventDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acorde': {
      id: '/acorde'
      path: '/acorde'
      fullPath: '/acorde'
      preLoaderRoute: typeof AcordeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutUs': {
      id: '/aboutUs'
      path: '/aboutUs'
      fullPath: '/aboutUs'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  AcordeRoute: AcordeRoute,
  CalendarioRoute: CalendarioRoute,
  ChatsRoute: ChatsRoute,
  EventDetailRoute: EventDetailRoute,
  GenericRoute: GenericRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NewEventRoute: NewEventRoute,
  NotificacionesRoute: NotificacionesRoute,
  OrganizadoresRoute: OrganizadoresRoute,
  PerfilRoute: PerfilRoute,
  RegisterRoute: RegisterRoute,
  SoporteRoute: SoporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
